jobs:
  - name: development
    max_in_flight: 1
    plan:
      - get: dataworks-rbac-munge-policies-infra
        trigger: true
      - get: dw-al2-ecs-ami
        resource: dw-al2-ecs-rbac-munge-ami
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
      - .: (( inject meta.plan.terraform-plan ))

