jobs:
  - name: dataworks-rbac-munge-policies-infra-pr
    plan:
      - get: dataworks-rbac-munge-policies-infra-pr
        trigger: true
        version: every
      - get: dw-al2-ecs-ami
        trigger: true
      - put: dataworks-rbac-munge-policies-infra-pr
        params:
          path: dataworks-rbac-munge-policies-infra-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-rbac-munge-policies-infra: dataworks-rbac-munge-policies-infra-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-rbac-munge-policies-infra: dataworks-rbac-munge-policies-infra-pr
        params:
          TF_WORKSPACE: "qa"
          DETAILED_EXITCODE: ""
        on_failure:
          put: dataworks-rbac-munge-policies-infra-pr
          params:
            path: dataworks-rbac-munge-policies-infra-pr
            status: failure
        on_success:
          put: dataworks-rbac-munge-policies-infra-pr
          params:
            path: dataworks-rbac-munge-policies-infra-pr
            status: success
