jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - get: dataworks-rbac-munge-policies-infra
        trigger: true
        passed:
          - qa
      - get: dw-al2-ecs-ami
        resource: dw-al2-ecs-rbac-munge-ami
        trigger: true
        passed:
          - qa
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'preprod'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'preprod'
